<a href="https://colab.research.google.com/github/gokhanturer/assignment/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [6]:
import numpy as np
import pandas as pd
import scipy as sp
import statistics as st

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [3]:
samples = np.random.normal(100, 15, 1000)
samples

array([ 94.2913749 , 112.51332905,  94.64042335, 117.98598142,
       118.15097529, 115.82473492,  96.71434244, 111.23605316,
        98.66568321,  97.41401641, 107.81493544,  98.67157263,
       100.92988944, 112.84770901, 113.41278245,  84.7658607 ,
        97.30095585,  97.76843357,  90.3256352 , 110.1142153 ,
        99.05788165,  96.69769937,  84.0944464 ,  74.90266558,
       108.15231097, 108.56674949, 111.69493123, 109.57563468,
       100.31342554,  88.68754437, 112.31094446, 100.8561909 ,
       112.92237076, 107.36393837,  80.95963442,  89.53085786,
        99.57659586, 113.52653641,  99.71971022,  83.57987034,
        80.20179553, 105.77704689,  97.22876625, 100.22388582,
       107.92624441,  82.61043123,  92.93448355,  77.94723139,
       124.03454763, 103.22848957, 114.86433782,  68.16200902,
        95.24821893, 110.99312064,  96.55190162, 105.36385788,
        99.86162412,  73.4141092 ,  94.80592887, 114.04404606,
        89.7118842 ,  84.85893259,  99.13987407, 106.66882978,
       105.4560601 , 125.20406623, 112.7527641 , 106.64285912,
        83.00698579, 118.33783753,  92.20194466,  99.42990728,
        83.94693612,  92.32988136,  98.28077285, 104.14569767,
        95.32494456, 115.58235077, 112.34769154,  96.15048207,
        68.57819837, 103.01140588,  90.49508207, 113.79620259,
       119.88330746, 105.0491162 , 127.16369022,  94.92769838,
       122.24949111, 100.70720005,  96.66540498, 110.41170825,
       110.90668231,  93.40619283,  94.1365708 ,  93.75250129,
       116.85817179,  89.89486864, 107.95117658, 111.70335631,
        96.86628206,  95.09998744,  78.6433938 , 121.59265869,
        85.37885127,  95.18284991, 131.24794024,  95.42189842,
       114.19547713, 108.71157411,  93.61071645,  93.48227876,
       108.46319827, 111.37706124,  92.65112754,  94.94611994,
        82.78055459,  58.89283986,  73.90664044, 112.37688237,
       109.8763864 , 111.93134057, 104.42783226, 100.94210461,
       102.79780394, 117.68981185,  98.32218062,  71.99376791,
       114.47549433, 102.0430224 , 116.70523783, 104.87892478,
        79.72192846, 100.80915079,  96.43602993, 100.4550928 ,
       108.40803204,  95.47334528,  98.33317157, 101.39353639,
       132.06678291,  92.37011015, 127.30815497, 109.1939143 ,
       141.59561452, 103.7311625 ,  60.48815932,  90.37764475,
        64.4081509 ,  82.85938057, 124.49652125,  95.56030503,
       100.15503916,  84.86714574, 116.69594074, 104.24415411,
       127.54063464, 112.11371683, 114.05102076, 104.15590411,
        98.04970004, 105.65047638,  95.2767212 ,  91.93138656,
       112.33949894, 119.4892923 , 101.98634004,  97.72551944,
       104.54309084,  94.17555616,  87.50006908,  94.71708361,
       108.7200641 ,  84.54078664,  97.86580128, 119.55793041,
        89.96909974,  90.98285119,  85.62648471,  84.87813925,
       102.59475332,  79.55067019, 104.88217303,  92.27140845,
        91.10825263, 110.65745942, 120.80597608,  97.59418202,
        87.09535112, 107.76931041,  88.52235066, 108.9298607 ,
        88.84329395,  94.47924881, 110.20153051, 120.71989282,
        83.76694711, 121.24928862, 105.50685203, 113.38825121,
       125.4195018 , 109.22291283, 103.52472539, 119.63851475,
        99.55195023,  78.88132127,  95.50035181, 114.46149147,
       111.38272121, 129.46444223,  98.1043576 , 108.08350393,
        96.68802221,  95.72306453, 109.99844409, 105.07137944,
       114.71007811, 126.56214655,  93.41049648,  86.53734047,
        86.63474789,  93.55432219, 109.24181929,  87.29667874,
        90.4011949 , 115.12134975, 114.26280502,  84.95256827,
        99.95216274,  90.4783432 ,  81.44593674,  92.92702536,
        93.64219609, 101.9335649 , 119.74126583,  88.02199133,
        82.07667708, 103.36334264, 105.87918312, 100.46415829,
        90.68709555,  82.12997439, 119.87256001, 114.66041894,
       118.06111146,  99.46804788,  83.24074714, 131.03280976,
       109.50993864,  82.77565231, 104.14343676,  89.97348221,
        88.73212153, 106.22267354,  84.47948804, 115.05416764,
        72.19765933, 107.45731283,  99.26496566, 115.04215896,
        93.86347904,  94.74367624, 108.63625242, 115.48090738,
        99.22225875,  87.95855097,  77.69654255,  94.77774994,
        89.79689821,  93.18480274,  92.34584303, 121.33725755,
        62.83380826,  94.70873198,  88.59185485, 108.70085905,
       102.66023232,  86.63430081,  93.78421299, 103.56227684,
        94.61007759, 109.46384334,  84.45225994,  81.91962541,
       110.44653234,  88.6977125 ,  94.45222125, 107.21151797,
        83.52965152,  93.15801841, 128.88360045, 119.91865891,
       102.87995648, 100.54790002, 113.7673227 , 115.13172089,
       101.22714955,  80.14959607,  98.60674432, 115.47741847,
        82.58876197, 106.84271618,  95.95944896, 116.61929189,
       101.16820863, 100.77373288,  78.12939534, 100.14384034,
        90.24809906,  91.21503115,  98.09690667,  81.62481966,
       109.70936793,  94.01473217, 109.34536662,  97.10828718,
        89.77430752, 119.62415964,  82.21330231,  68.22547962,
       103.29828264,  68.3094666 ,  99.70288943, 112.53049066,
       110.44331663,  94.05044677,  92.1139847 , 112.79334961,
        89.26082848,  81.55077143, 119.55079791,  99.57583201,
       125.83458888, 102.53438605,  91.83795365, 109.80582493,
       104.09445856,  85.24412492, 102.88634801,  72.2881581 ,
       105.45711944, 115.88433991,  91.70418046, 102.85551154,
       119.24540873,  66.45889953,  83.74658753,  90.92429078,
        80.57466712,  92.68838081,  94.97479489, 104.6935776 ,
        95.42949984, 110.45186101, 102.24957909, 116.49487823,
       109.43316917, 121.05687744, 107.65396363, 123.22079193,
       122.80608159, 125.98575102,  96.27251492,  97.91090374,
        85.85484661,  92.62604564,  81.4115268 , 118.8095397 ,
        93.10543745,  88.98610896, 110.32954732, 105.69384134,
        97.61451679, 114.94950586,  98.14271806, 119.84441374,
       112.45075206, 116.10699466,  82.71358994, 108.41887783,
       104.33618654, 118.05421469,  98.16374746, 103.88040713,
       112.59374784,  98.2272595 ,  87.86242092,  73.99699363,
       108.18788159,  59.1648371 ,  90.71124879, 105.49844718,
       120.20014716,  87.35630112, 102.93131689,  78.88303398,
        82.12146746, 102.05817126,  96.75732913,  94.09532989,
       115.21265645, 102.55087533, 100.11978349, 107.26691389,
       104.0479985 , 125.32587526, 109.03360167, 117.42010446,
        74.18546379, 113.46237094,  82.94973157,  83.87281757,
        99.03806535, 122.29803762,  86.96394887,  98.86969979,
       101.38104916, 116.77159239, 125.78488581, 116.98578507,
       103.33826781, 108.99978002,  89.87298189, 103.88510837,
        82.23492262,  65.84558485, 101.47314299, 112.95729395,
        84.6531891 ,  86.84714438,  87.40477515,  78.16073942,
        96.79871297, 112.50760158, 115.64962883,  94.73984055,
       119.0850392 , 117.36144637, 104.709387  ,  95.69658445,
       104.01503635, 105.13927559, 107.80858077, 103.54597324,
        95.42800611,  99.32315266,  89.35141276,  80.52452202,
        91.47761701, 100.89767204,  93.2505814 , 109.85137848,
       110.82350403,  86.24773254, 119.50071925,  98.14173819,
       109.61629273,  97.64960231, 120.78839023, 110.53026178,
        87.801053  ,  97.70405258,  93.22674936,  90.92558023,
        83.60896156,  94.85033319,  98.47860238, 105.2884181 ,
       116.09318884, 104.36089508,  88.9499672 , 116.23459711,
        99.52586459,  90.61378068, 107.98510919, 111.98828358,
       109.26431671, 122.21910959, 110.70403772, 107.09806047,
       100.49886593,  99.09528871,  91.29671552, 109.18286086,
       121.59534027,  94.22143782, 118.88498189,  90.89147397,
        77.4949289 ,  61.69852186, 101.04908815,  90.88942944,
       103.00227744, 125.15698765, 118.95805934,  77.48723915,
       110.86285165,  75.216071  ,  89.26607686,  88.35727195,
       108.75446804,  94.67218701, 121.05837774,  72.96329538,
        86.24418623,  88.21165968, 104.77993887,  88.72086573,
        86.98090369,  90.65955079,  93.99303986, 129.15218172,
        93.38442502, 103.71395944,  86.08684876,  82.35584329,
        76.0496434 , 101.63346527,  89.57917942,  93.29326344,
       102.23620002,  69.64110985,  85.77506829,  98.33183272,
       113.2582731 ,  71.29488449,  92.09640315,  97.61828271,
        88.6656244 , 107.48348603, 115.57882302, 100.10569394,
        96.40820672, 113.23072615, 122.21630763,  87.66360281,
        84.61822907, 109.66234207,  95.43335736, 116.05153854,
        96.96122699, 113.79203465,  95.03534283, 116.49318892,
       114.00728706,  99.70600113, 117.3526257 ,  68.21001654,
        94.4454285 ,  92.16903976,  56.77758519, 118.04599265,
        76.41172296,  94.04198037, 113.6283117 ,  70.36500745,
       138.52282759, 140.49733556,  82.30928526, 103.60466313,
        76.17388457, 128.21113102, 118.1728709 ,  89.97043563,
       113.49060073, 108.62508916,  94.57893448, 105.41363148,
       105.68509491,  86.60606938, 111.34873676, 103.41963457,
       100.06709019, 108.53037846,  93.83309388, 109.46792757,
       117.75789604,  54.94088568,  90.3923539 , 124.72126212,
       119.50833955,  78.65745644,  74.78761815, 119.95122077,
       104.27505542, 104.29048762,  70.96220117, 108.27078089,
        82.01908679,  78.18854246, 100.04092921, 101.71444005,
       121.0234544 , 101.79827802,  77.28029206, 100.53605136,
        81.27613597, 103.43676484,  98.42794626,  83.00605216,
        93.80396241,  79.01879874,  83.29253563, 103.15437355,
       112.29154987, 137.82096694,  84.80876518,  88.98602909,
        87.97392886, 106.58522429,  82.28397972, 110.13530861,
       100.48376133,  98.39468841,  76.92171937,  97.76063097,
       119.7027701 ,  82.2797469 ,  80.51728998,  94.57131188,
       106.34371587, 111.40777611, 104.80983769, 106.31283908,
        76.86422703,  95.6770301 ,  82.72599323, 108.29529019,
        84.37040579,  90.27117552,  94.75983521, 108.95502961,
       101.72190027, 106.72283862, 121.54102457, 101.83011215,
       123.47794558, 137.23358345, 113.62695195,  84.31229525,
       104.0651093 ,  98.52197013,  88.37608996,  89.96732643,
       111.87884839, 118.15418   , 109.89687389,  92.24074022,
       102.14304074, 108.34285603,  88.38000149,  89.05866564,
       112.1666447 ,  79.17780234,  94.41834955, 117.2306636 ,
        82.22725599, 104.968042  ,  88.09680387, 101.13591064,
       110.10308294,  89.97714905, 105.18669681,  86.20481912,
        91.4494596 ,  92.21799031,  80.3610146 , 113.44044093,
       126.71118361,  91.4554346 , 103.07848782,  82.2060689 ,
       106.67733096,  93.81763137,  94.07438325,  88.25213574,
        98.41055916, 116.2861402 ,  98.76638959,  92.81838488,
       119.49415663, 123.43222735,  74.3247387 , 129.34600844,
        95.25362133,  98.94492173,  94.49329135,  78.35252546,
        94.28457783,  89.69105725,  89.87185534,  77.83494194,
       119.22387016,  61.33214408, 115.19804454, 131.02392862,
       108.06308363,  83.88120636, 114.60819376, 113.37313112,
       112.19053452,  76.1164673 , 120.68310829,  94.19228578,
       101.43163651, 120.57688232, 103.44553838, 104.51105528,
       106.83533512,  74.30753819,  86.47232984,  87.50038064,
       101.81363417,  95.61533241,  86.19499412,  83.27601369,
        54.38692064, 101.67112151,  95.66574303, 101.7500449 ,
        99.20496971, 139.42806818,  97.13132002,  89.70150478,
        69.9887615 , 107.1746158 ,  81.85989797, 119.4555943 ,
       112.44604536,  98.45422189, 100.34600803,  81.28320059,
       102.83002315, 112.21166758,  85.26154596,  90.23329828,
        80.56407427, 104.81085825, 116.18664198,  94.09292323,
        92.99961432,  86.54183778, 114.32919933, 101.51414808,
       114.95867992, 111.26064904, 117.13792408, 106.24536784,
        98.41241267, 105.67356568,  86.39780485,  99.23213274,
       105.30788404,  84.55218124, 104.52731225, 107.25713126,
       130.60502462, 101.96199503,  98.79373602,  88.92254717,
        93.68703016, 134.95604097, 109.62258466,  96.46272749,
       126.22827133,  78.6136563 ,  74.99326375, 116.26422169,
       120.78560032,  72.86820005, 104.01389868,  82.67725673,
        92.17196879,  74.7283682 , 119.73833678,  77.78188995,
       122.18113927,  85.90835302, 100.58142387,  96.22777097,
       116.69029471, 100.97578592,  79.82543557, 124.60643882,
       133.46945096, 102.4592118 , 120.066862  , 116.46947233,
        57.7238719 , 106.52382931, 113.31869251, 110.06290862,
        93.41434536,  80.51519572,  96.3201727 , 119.06569116,
       106.45577003, 100.96793042,  97.94932262, 116.39429107,
       116.55507576,  92.95864421, 113.26935034,  79.19228118,
       117.66743524,  91.02414251,  78.99919576,  84.29038169,
        95.23449377, 118.77993969,  94.76195621, 103.48143714,
       134.65385009, 103.1168607 ,  94.32191811,  67.70431107,
        86.95541189, 103.84856343, 112.01936755, 106.80076667,
       111.50398889,  96.74493299,  72.28247047, 113.26008788,
       109.41183991, 108.86364098,  70.64044999, 112.86045753,
       130.00028596,  96.77926576, 119.86347031,  85.59778327,
        85.46481845,  86.16246507, 103.24247478,  99.933048  ,
        90.20879607,  87.88376441, 109.52762902,  91.22383381,
       108.45199007,  81.44017326,  91.07602313, 112.77588708,
        95.37660611, 134.23873541, 100.67150517,  63.18289948,
       103.84977017, 107.14287463,  65.63383196, 103.14707779,
       113.33901373, 106.00715197,  70.91535266, 122.19348726,
       110.22638715,  95.28491039, 121.14007109, 104.48357989,
        96.3502729 ,  95.84535414,  99.02878907,  88.52176172,
       108.39975685, 120.37205698,  83.14682302,  78.55697965,
       104.81374731, 100.53218294,  82.04294091,  83.34137822,
       103.72544635, 110.33667346,  98.13128234, 104.39289903,
       105.14637137,  83.86702115, 101.84419709,  99.5523757 ,
       107.97877797,  89.35705042, 108.02213224,  75.57277678,
        91.60379678, 101.38448744,  92.59437419,  90.24945029,
       100.91731072, 112.25456831,  96.72018533,  95.96873694,
       110.74711989,  83.67481302,  72.46714768, 104.48903391,
        92.05782162,  97.80110228, 104.30874733, 107.13635869,
       107.23241894,  83.07296317,  96.86128892, 121.15781573,
        92.43309431, 103.02388625, 100.41472494,  88.12261819,
       130.86718824,  94.48260676, 126.65762141,  89.68068679,
        95.25323442,  83.41977999, 126.41528014, 101.05351285,
        94.47555001, 109.28478038,  99.91190577,  83.22736805,
        76.18502766, 103.9193018 , 108.63816645,  98.95265333,
       108.19400179,  96.37741757,  97.13996471,  93.48691661,
        53.42154644, 104.11003381, 109.20224137,  84.35657752,
        92.52035509,  86.62419477,  89.51036774,  90.93822   ,
       131.79892165, 105.38586302,  79.35451652,  97.32113656,
       113.33573985,  98.21661533, 103.58034769,  97.77573603,
       128.85700696, 119.07669158, 102.30926548,  84.73213252,
       113.86176687,  88.48727008, 101.12347505,  98.99958143,
        96.81765178,  65.48406681, 119.19750735, 107.69285293,
        70.83563638, 111.14395602, 113.1401842 ,  96.10533555,
        74.93642875,  80.98356449,  86.41390457,  87.24593904,
        75.01093167,  68.83165935, 122.92945647, 107.99869559,
       123.83888182, 103.26057404, 111.84035904, 104.28001402,
        86.90688268,  76.61882442,  89.89719376,  92.16929108,
       108.54626387,  76.75275152, 129.92399384,  90.65173337,
        86.90065122,  60.02183017, 122.0420733 , 101.94152198,
       116.11232596,  77.70765386, 121.360868  , 113.46844954,
        84.78810059,  85.97882368,  80.10350473, 110.39719961,
        94.60374455, 114.44302486, 119.08645287, 101.23658948,
        70.99718109,  81.60200624,  94.51251885, 109.63891768])

Compute the **mean**, **median**, and **mode**

In [29]:
mean = samples.mean()
mean
median = np.median(samples)
median
mode = stats.mode(samples)
mode

ModeResult(mode=array([53.42154644]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [12]:
min = np.min(samples)
max =np.max(samples)
q1 = np.percentile(samples, 25, interpolation="midpoint")
q1
q3 = np.percentile(samples, 75, interpolation="midpoint")
q3
iqr = q3-q1
iqr

20.33989991670569

Compute the **variance** and **standard deviation**

In [28]:
variance = np.var(samples)
std_dev = np.std(samples)
std_dev
from scipy import stats as stats

Compute the **skewness** and **kurtosis**

In [35]:
skewness = stats.skew(samples, bias=False)
kurtosis = stats.kurtosis(samples)
kurtosis

-0.05258635506652665

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [21]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [23]:
y = np.array(np.linspace(1,10,10))
y

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [24]:
r = np.corrcoef(x,y)
r

array([[1., 1.],
       [1., 1.]])

## Pandas Correlation Calculation

Run the code below

In [25]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [27]:
r = np.corrcoef(x,y)
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho = stats.spearmanr(x,y)

## Seaborn Dataset Tips

Import Seaborn Library

In [37]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [39]:
tips = sns.load_dataset("tips")
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [40]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [43]:
np.corrcoef(tips["total_bill"],tips["tip"])

array([[1.        , 0.67573411],
       [0.67573411, 1.        ]])